import { SkillCardProp } from "./types";

const skills: SkillCardProp[] = [
  {
    imageUrl: "/assets/icons/icons8-html-5.svg",
    label: "HTML",
    learning: false,
    background: "rgba(255, 98, 0, 0.055)",
    type: "Current",
  },
  {
    imageUrl: "/assets/icons/icons8-css3.svg",
    label: "CSS",
    learning: false,
    background: "rgba(0, 157, 230, 0.055)",
    type: "Current",
  },
  {
    imageUrl: "/assets/icons/icons8-javascript.svg",
    label: "JavaScript",
    learning: false,
    background: "rgba(254, 221, 35, 0.15)",
    type: "Current",
  },
  {
    imageUrl: "/assets/icons/icons8-nodejs.svg",
    label: "Node JS",
    learning: false,
    background: "rgba(94, 170, 98.055, 0.077)",
    type: "Old",
  },
  {
    imageUrl: "/assets/icons/icons8-react-native.svg",
    label: "React",
    learning: false,
    background: "rgba(77, 223, 236, 0.055)",
    type: "Current",
  },
  {
    imageUrl: "/assets/icons/icons8-graphql.svg",
    label: "GraphQL",
    learning: false,
    background: "rgba(255, 35, 119, 0.055)",
    type: "Current",
  },
  {
    imageUrl: "/assets/icons/icons8-apollo.svg",
    label: "Apollo Client",
    learning: false,
    background: "rgba(85, 44, 167, 0.055)",
    type: "Current",
  },
  {
    imageUrl: "/assets/icons/icons8-material-ui.svg",
    label: "Material UI",
    learning: false,
    background: "rgba(0, 157, 230, 0.055)",
    type: "Current",
  },
  {
    imageUrl: "/assets/icons/icons8-tailwind-css.svg",
    label: "Tailwind",
    learning: false,
    background: "rgba(0, 157, 230, 0.055)",
    type: "Current",
  },
  {
    imageUrl: "/assets/icons/icons8-typescript.svg",
    label: "TypeScript",
    learning: false,
    background: "rgba(0, 157, 230, 0.055)",
    type: "Current",
  },
  {
    imageUrl: "/assets/icons/icons8-nextjs.svg",
    label: "Next JS",
    learning: true,
    background: "rgba(255, 255, 255, 0.055)",
    type: "New/Exploring",
  },
  // {
  //   imageUrl: "/assets/icons/icons8-flutter.svg",
  //   label: "Flutter",
  //   learning: false,
  //   background: "rgba(0, 199, 255, 0.077)",
  //   type: "Heard of",
  // },
  {
    imageUrl: "/assets/icons/icons8-jquery.svg",
    label: "jQuery",
    learning: false,
    background: "rgba(110, 135, 184, 0.077)",
    type: "Old",
  },
  {
    imageUrl: "/assets/icons/icons8-php.svg",
    label: "PHP",
    learning: false,
    background: "rgba(110, 135, 184, 0.077)",
    type: "Old",
  },
  {
    imageUrl: "/assets/icons/icons8-mysql.svg",
    label: "MySQL",
    learning: false,
    background: "rgba(0, 121, 107, 0.055)",
    type: "Old",
  },
  // {
  //   imageUrl: "/assets/icons/icons8-redux.svg",
  //   label: "Redux",
  //   learning: false,
  //   background: "rgba(132, 85, 192, 0.077)",
  //   type: "Heard of",
  // },
  {
    imageUrl: "/assets/icons/icons8-sass.svg",
    label: "Sass",
    learning: false,
    background: "rgba(255, 87, 139, 0.077)",
    type: "Old",
  },
  {
    imageUrl: "/assets/icons/icons8-git.svg",
    label: "Git",
    learning: false,
    background: "rgba(255, 65, 0, 0.066)",
    type: "Current",
  },
  {
    imageUrl: "/assets/icons/zustand-removebg-preview.png",
    label: "Zustand",
    learning: false,
    background: "rgba(194, 123, 103, 0.066)",
    type: "Current",
  },
  {
    imageUrl: "/assets/icons/icons8-google-cloud.svg",
    label: "Google Cloud",
    learning: false,
    background: "rgba(200, 200, 200, 0.077)",
    type: "Current",
  },
];

export default skills;